name: format

on:
  push

jobs:
  format:
    name: Format
    permissions:
      contents: write
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Auto format
        run: npm run format

      - name: Commit and push if changed
        run: |
          git config user.name 'Auto-formatter'
          git config user.email 'Lladnaar@users.noreply.github.com'
          git diff --quiet || git commit -am "Automatic formating"
          git push
