name: integrate

on:
  pull_request:
    branches: [main]

jobs:
  style:
    name: Style
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Select branch
        run: git switch ${{github.head_ref}}

      - name: Auto format
        run: npm run format

      - name: Commit and push if changed
        run: git diff --quiet || git -c user.name=integrate -c user.email=integrate@github commit -a -m "Automatic format" && git push

      - name: Lint project
        run: npm run lint

  server-test:
    name: Server Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup redis
        uses: supercharge/redis-github-action@1.2.0
        with: 
          redis-version: 8

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Start server
        run: npm run start &

      - name: Run tests
        run: npm run test

  client-test:
    name: Client Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup redis
        uses: supercharge/redis-github-action@1.2.0
        with: 
          redis-version: 8

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
            name: playwright-report
            path: playwright-report/
            retention-days: 30
